package com.cloud.service.domain.dao;

import com.cloud.service.domain.model.Farm;
import com.cloud.service.domain.model.FarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int countByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int deleteByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int insert(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int insertSelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    List<Farm> selectByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    Farm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") Farm record, @Param("example") FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int updateByExample(@Param("record") Farm record, @Param("example") FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int updateByPrimaryKeySelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    int updateByPrimaryKey(Farm record);
}