package com.cloud.service.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FarmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public FarmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameIsNull() {
            addCriterion("scalr_farm_name is null");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameIsNotNull() {
            addCriterion("scalr_farm_name is not null");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameEqualTo(String value) {
            addCriterion("scalr_farm_name =", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameNotEqualTo(String value) {
            addCriterion("scalr_farm_name <>", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameGreaterThan(String value) {
            addCriterion("scalr_farm_name >", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameGreaterThanOrEqualTo(String value) {
            addCriterion("scalr_farm_name >=", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameLessThan(String value) {
            addCriterion("scalr_farm_name <", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameLessThanOrEqualTo(String value) {
            addCriterion("scalr_farm_name <=", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameLike(String value) {
            addCriterion("scalr_farm_name like", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameNotLike(String value) {
            addCriterion("scalr_farm_name not like", value, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameIn(List<String> values) {
            addCriterion("scalr_farm_name in", values, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameNotIn(List<String> values) {
            addCriterion("scalr_farm_name not in", values, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameBetween(String value1, String value2) {
            addCriterion("scalr_farm_name between", value1, value2, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmNameNotBetween(String value1, String value2) {
            addCriterion("scalr_farm_name not between", value1, value2, "scalrFarmName");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdIsNull() {
            addCriterion("scalr_farm_id is null");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdIsNotNull() {
            addCriterion("scalr_farm_id is not null");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdEqualTo(String value) {
            addCriterion("scalr_farm_id =", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdNotEqualTo(String value) {
            addCriterion("scalr_farm_id <>", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdGreaterThan(String value) {
            addCriterion("scalr_farm_id >", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdGreaterThanOrEqualTo(String value) {
            addCriterion("scalr_farm_id >=", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdLessThan(String value) {
            addCriterion("scalr_farm_id <", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdLessThanOrEqualTo(String value) {
            addCriterion("scalr_farm_id <=", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdLike(String value) {
            addCriterion("scalr_farm_id like", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdNotLike(String value) {
            addCriterion("scalr_farm_id not like", value, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdIn(List<String> values) {
            addCriterion("scalr_farm_id in", values, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdNotIn(List<String> values) {
            addCriterion("scalr_farm_id not in", values, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdBetween(String value1, String value2) {
            addCriterion("scalr_farm_id between", value1, value2, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrFarmIdNotBetween(String value1, String value2) {
            addCriterion("scalr_farm_id not between", value1, value2, "scalrFarmId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdIsNull() {
            addCriterion("scalr_env_id is null");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdIsNotNull() {
            addCriterion("scalr_env_id is not null");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdEqualTo(String value) {
            addCriterion("scalr_env_id =", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdNotEqualTo(String value) {
            addCriterion("scalr_env_id <>", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdGreaterThan(String value) {
            addCriterion("scalr_env_id >", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdGreaterThanOrEqualTo(String value) {
            addCriterion("scalr_env_id >=", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdLessThan(String value) {
            addCriterion("scalr_env_id <", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdLessThanOrEqualTo(String value) {
            addCriterion("scalr_env_id <=", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdLike(String value) {
            addCriterion("scalr_env_id like", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdNotLike(String value) {
            addCriterion("scalr_env_id not like", value, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdIn(List<String> values) {
            addCriterion("scalr_env_id in", values, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdNotIn(List<String> values) {
            addCriterion("scalr_env_id not in", values, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdBetween(String value1, String value2) {
            addCriterion("scalr_env_id between", value1, value2, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEnvIdNotBetween(String value1, String value2) {
            addCriterion("scalr_env_id not between", value1, value2, "scalrEnvId");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointIsNull() {
            addCriterion("scalr_endpoint is null");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointIsNotNull() {
            addCriterion("scalr_endpoint is not null");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointEqualTo(String value) {
            addCriterion("scalr_endpoint =", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointNotEqualTo(String value) {
            addCriterion("scalr_endpoint <>", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointGreaterThan(String value) {
            addCriterion("scalr_endpoint >", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointGreaterThanOrEqualTo(String value) {
            addCriterion("scalr_endpoint >=", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointLessThan(String value) {
            addCriterion("scalr_endpoint <", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointLessThanOrEqualTo(String value) {
            addCriterion("scalr_endpoint <=", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointLike(String value) {
            addCriterion("scalr_endpoint like", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointNotLike(String value) {
            addCriterion("scalr_endpoint not like", value, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointIn(List<String> values) {
            addCriterion("scalr_endpoint in", values, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointNotIn(List<String> values) {
            addCriterion("scalr_endpoint not in", values, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointBetween(String value1, String value2) {
            addCriterion("scalr_endpoint between", value1, value2, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andScalrEndpointNotBetween(String value1, String value2) {
            addCriterion("scalr_endpoint not between", value1, value2, "scalrEndpoint");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNull() {
            addCriterion("system_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNotNull() {
            addCriterion("system_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNameEqualTo(String value) {
            addCriterion("system_name =", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotEqualTo(String value) {
            addCriterion("system_name <>", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThan(String value) {
            addCriterion("system_name >", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_name >=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThan(String value) {
            addCriterion("system_name <", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThanOrEqualTo(String value) {
            addCriterion("system_name <=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLike(String value) {
            addCriterion("system_name like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotLike(String value) {
            addCriterion("system_name not like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameIn(List<String> values) {
            addCriterion("system_name in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotIn(List<String> values) {
            addCriterion("system_name not in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameBetween(String value1, String value2) {
            addCriterion("system_name between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotBetween(String value1, String value2) {
            addCriterion("system_name not between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("register_time is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("register_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("register_time =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("register_time <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("register_time >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("register_time >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("register_time <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("register_time <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("register_time in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("register_time not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("register_time between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("register_time not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionIsNull() {
            addCriterion("current_version is null");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionIsNotNull() {
            addCriterion("current_version is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionEqualTo(String value) {
            addCriterion("current_version =", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionNotEqualTo(String value) {
            addCriterion("current_version <>", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionGreaterThan(String value) {
            addCriterion("current_version >", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionGreaterThanOrEqualTo(String value) {
            addCriterion("current_version >=", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionLessThan(String value) {
            addCriterion("current_version <", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionLessThanOrEqualTo(String value) {
            addCriterion("current_version <=", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionLike(String value) {
            addCriterion("current_version like", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionNotLike(String value) {
            addCriterion("current_version not like", value, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionIn(List<String> values) {
            addCriterion("current_version in", values, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionNotIn(List<String> values) {
            addCriterion("current_version not in", values, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionBetween(String value1, String value2) {
            addCriterion("current_version between", value1, value2, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andCurrentVersionNotBetween(String value1, String value2) {
            addCriterion("current_version not between", value1, value2, "currentVersion");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalIsNull() {
            addCriterion("monitoring_interval is null");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalIsNotNull() {
            addCriterion("monitoring_interval is not null");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalEqualTo(String value) {
            addCriterion("monitoring_interval =", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalNotEqualTo(String value) {
            addCriterion("monitoring_interval <>", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalGreaterThan(String value) {
            addCriterion("monitoring_interval >", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalGreaterThanOrEqualTo(String value) {
            addCriterion("monitoring_interval >=", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalLessThan(String value) {
            addCriterion("monitoring_interval <", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalLessThanOrEqualTo(String value) {
            addCriterion("monitoring_interval <=", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalLike(String value) {
            addCriterion("monitoring_interval like", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalNotLike(String value) {
            addCriterion("monitoring_interval not like", value, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalIn(List<String> values) {
            addCriterion("monitoring_interval in", values, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalNotIn(List<String> values) {
            addCriterion("monitoring_interval not in", values, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalBetween(String value1, String value2) {
            addCriterion("monitoring_interval between", value1, value2, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andMonitoringIntervalNotBetween(String value1, String value2) {
            addCriterion("monitoring_interval not between", value1, value2, "monitoringInterval");
            return (Criteria) this;
        }

        public Criteria andFarmTypeIsNull() {
            addCriterion("farm_type is null");
            return (Criteria) this;
        }

        public Criteria andFarmTypeIsNotNull() {
            addCriterion("farm_type is not null");
            return (Criteria) this;
        }

        public Criteria andFarmTypeEqualTo(String value) {
            addCriterion("farm_type =", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeNotEqualTo(String value) {
            addCriterion("farm_type <>", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeGreaterThan(String value) {
            addCriterion("farm_type >", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("farm_type >=", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeLessThan(String value) {
            addCriterion("farm_type <", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeLessThanOrEqualTo(String value) {
            addCriterion("farm_type <=", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeLike(String value) {
            addCriterion("farm_type like", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeNotLike(String value) {
            addCriterion("farm_type not like", value, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeIn(List<String> values) {
            addCriterion("farm_type in", values, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeNotIn(List<String> values) {
            addCriterion("farm_type not in", values, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeBetween(String value1, String value2) {
            addCriterion("farm_type between", value1, value2, "farmType");
            return (Criteria) this;
        }

        public Criteria andFarmTypeNotBetween(String value1, String value2) {
            addCriterion("farm_type not between", value1, value2, "farmType");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameIsNull() {
            addCriterion("jenkins_job_name is null");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameIsNotNull() {
            addCriterion("jenkins_job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameEqualTo(String value) {
            addCriterion("jenkins_job_name =", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameNotEqualTo(String value) {
            addCriterion("jenkins_job_name <>", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameGreaterThan(String value) {
            addCriterion("jenkins_job_name >", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("jenkins_job_name >=", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameLessThan(String value) {
            addCriterion("jenkins_job_name <", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameLessThanOrEqualTo(String value) {
            addCriterion("jenkins_job_name <=", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameLike(String value) {
            addCriterion("jenkins_job_name like", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameNotLike(String value) {
            addCriterion("jenkins_job_name not like", value, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameIn(List<String> values) {
            addCriterion("jenkins_job_name in", values, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameNotIn(List<String> values) {
            addCriterion("jenkins_job_name not in", values, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameBetween(String value1, String value2) {
            addCriterion("jenkins_job_name between", value1, value2, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andJenkinsJobNameNotBetween(String value1, String value2) {
            addCriterion("jenkins_job_name not between", value1, value2, "jenkinsJobName");
            return (Criteria) this;
        }

        public Criteria andIsRunningIsNull() {
            addCriterion("is_running is null");
            return (Criteria) this;
        }

        public Criteria andIsRunningIsNotNull() {
            addCriterion("is_running is not null");
            return (Criteria) this;
        }

        public Criteria andIsRunningEqualTo(Boolean value) {
            addCriterion("is_running =", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotEqualTo(Boolean value) {
            addCriterion("is_running <>", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningGreaterThan(Boolean value) {
            addCriterion("is_running >", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_running >=", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningLessThan(Boolean value) {
            addCriterion("is_running <", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningLessThanOrEqualTo(Boolean value) {
            addCriterion("is_running <=", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningIn(List<Boolean> values) {
            addCriterion("is_running in", values, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotIn(List<Boolean> values) {
            addCriterion("is_running not in", values, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningBetween(Boolean value1, Boolean value2) {
            addCriterion("is_running between", value1, value2, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_running not between", value1, value2, "isRunning");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameIsNull() {
            addCriterion("scalr_env_name is null");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameIsNotNull() {
            addCriterion("scalr_env_name is not null");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameEqualTo(String value) {
            addCriterion("scalr_env_name =", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameNotEqualTo(String value) {
            addCriterion("scalr_env_name <>", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameGreaterThan(String value) {
            addCriterion("scalr_env_name >", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameGreaterThanOrEqualTo(String value) {
            addCriterion("scalr_env_name >=", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameLessThan(String value) {
            addCriterion("scalr_env_name <", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameLessThanOrEqualTo(String value) {
            addCriterion("scalr_env_name <=", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameLike(String value) {
            addCriterion("scalr_env_name like", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameNotLike(String value) {
            addCriterion("scalr_env_name not like", value, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameIn(List<String> values) {
            addCriterion("scalr_env_name in", values, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameNotIn(List<String> values) {
            addCriterion("scalr_env_name not in", values, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameBetween(String value1, String value2) {
            addCriterion("scalr_env_name between", value1, value2, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andScalrEnvNameNotBetween(String value1, String value2) {
            addCriterion("scalr_env_name not between", value1, value2, "scalrEnvName");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNull() {
            addCriterion("system_type is null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNotNull() {
            addCriterion("system_type is not null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeEqualTo(String value) {
            addCriterion("system_type =", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotEqualTo(String value) {
            addCriterion("system_type <>", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThan(String value) {
            addCriterion("system_type >", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("system_type >=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThan(String value) {
            addCriterion("system_type <", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThanOrEqualTo(String value) {
            addCriterion("system_type <=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLike(String value) {
            addCriterion("system_type like", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotLike(String value) {
            addCriterion("system_type not like", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIn(List<String> values) {
            addCriterion("system_type in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotIn(List<String> values) {
            addCriterion("system_type not in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeBetween(String value1, String value2) {
            addCriterion("system_type between", value1, value2, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotBetween(String value1, String value2) {
            addCriterion("system_type not between", value1, value2, "systemType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table farm
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 12 14:57:10 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table farm
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}