package com.cloud.service.domain.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
@XmlRootElement(name = "farm")
public class Farm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.scalr_farm_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String scalrFarmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.scalr_farm_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String scalrFarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.scalr_env_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String scalrEnvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.scalr_endpoint
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String scalrEndpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.system_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.register_time
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.current_version
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String currentVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.account_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.monitoring_interval
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String monitoringInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.farm_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String farmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.jenkins_job_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String jenkinsJobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.is_running
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private Boolean isRunning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.scalr_env_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String scalrEnvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.system_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    private String systemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.id
     *
     * @return the value of farm.id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.id
     *
     * @param id the value for farm.id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.scalr_farm_name
     *
     * @return the value of farm.scalr_farm_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getScalrFarmName() {
        return scalrFarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.scalr_farm_name
     *
     * @param scalrFarmName the value for farm.scalr_farm_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setScalrFarmName(String scalrFarmName) {
        this.scalrFarmName = scalrFarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.scalr_farm_id
     *
     * @return the value of farm.scalr_farm_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getScalrFarmId() {
        return scalrFarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.scalr_farm_id
     *
     * @param scalrFarmId the value for farm.scalr_farm_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setScalrFarmId(String scalrFarmId) {
        this.scalrFarmId = scalrFarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.scalr_env_id
     *
     * @return the value of farm.scalr_env_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getScalrEnvId() {
        return scalrEnvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.scalr_env_id
     *
     * @param scalrEnvId the value for farm.scalr_env_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setScalrEnvId(String scalrEnvId) {
        this.scalrEnvId = scalrEnvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.scalr_endpoint
     *
     * @return the value of farm.scalr_endpoint
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getScalrEndpoint() {
        return scalrEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.scalr_endpoint
     *
     * @param scalrEndpoint the value for farm.scalr_endpoint
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setScalrEndpoint(String scalrEndpoint) {
        this.scalrEndpoint = scalrEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.system_name
     *
     * @return the value of farm.system_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.system_name
     *
     * @param systemName the value for farm.system_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.register_time
     *
     * @return the value of farm.register_time
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.register_time
     *
     * @param registerTime the value for farm.register_time
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.current_version
     *
     * @return the value of farm.current_version
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getCurrentVersion() {
        return currentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.current_version
     *
     * @param currentVersion the value for farm.current_version
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setCurrentVersion(String currentVersion) {
        this.currentVersion = currentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.account_id
     *
     * @return the value of farm.account_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.account_id
     *
     * @param accountId the value for farm.account_id
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.monitoring_interval
     *
     * @return the value of farm.monitoring_interval
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getMonitoringInterval() {
        return monitoringInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.monitoring_interval
     *
     * @param monitoringInterval the value for farm.monitoring_interval
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setMonitoringInterval(String monitoringInterval) {
        this.monitoringInterval = monitoringInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.farm_type
     *
     * @return the value of farm.farm_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getFarmType() {
        return farmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.farm_type
     *
     * @param farmType the value for farm.farm_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setFarmType(String farmType) {
        this.farmType = farmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.jenkins_job_name
     *
     * @return the value of farm.jenkins_job_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getJenkinsJobName() {
        return jenkinsJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.jenkins_job_name
     *
     * @param jenkinsJobName the value for farm.jenkins_job_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setJenkinsJobName(String jenkinsJobName) {
        this.jenkinsJobName = jenkinsJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.is_running
     *
     * @return the value of farm.is_running
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public Boolean getIsRunning() {
        return isRunning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.is_running
     *
     * @param isRunning the value for farm.is_running
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setIsRunning(Boolean isRunning) {
        this.isRunning = isRunning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.scalr_env_name
     *
     * @return the value of farm.scalr_env_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getScalrEnvName() {
        return scalrEnvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.scalr_env_name
     *
     * @param scalrEnvName the value for farm.scalr_env_name
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setScalrEnvName(String scalrEnvName) {
        this.scalrEnvName = scalrEnvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.system_type
     *
     * @return the value of farm.system_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.system_type
     *
     * @param systemType the value for farm.system_type
     *
     * @mbggenerated Mon Jan 12 14:57:10 CST 2015
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType;
    }
}